### ISSUE TITLE
Doesn't load global plugins?

### ISSUE THREAD

**Issue by dwijnand** [coursier/sbt-launcher#37]
I have a small number of global utility plugins that I use across various builds, particularly sbt-project-graph and sbt-dependency-graph.

It looks like using this launcher global plugins aren't loaded?  If you can't reproduce, I'll try and put together a minimal reproduction.

The workaround I've been using is to temporarily copy and paste the global plugin definition into `project/plugins.sbt`.

**Comment by alexarchambault** [comment]
Must have been an occurrence of https://github.com/scalameta/metals/issues/567 (global plugins ignored from sbt-coursier `1.1.0-M12` to `1.1.0-M13-1`), fixed by https://github.com/coursier/sbt-coursier/pull/47. @dwijnand Re-open if that's not the case.

**Comment by dwijnand** [comment]
Which version of sbt-coursier does coursier/sbt-extras use?  I'm getting confused on the versions.

**Comment by alexarchambault** [comment]
The current master (using launcher `1.2.9`) uses sbt-coursier `1.1.0-M13-2` by default (the one used in the sbt-launcher build), which should be fine.

**Comment by dwijnand** [comment]
Then I suspect this is still an issue.  But I'll re-open when I'm reproducing the issue.
